// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2dJCDVZVMRYjHQHRKE-FyTPipZXPSL4',
    appId: '1:858390713760:web:761a578aaa2d79957b40c5',
    messagingSenderId: '858390713760',
    projectId: 'rentailappfl',
    authDomain: 'rentailappfl.firebaseapp.com',
    storageBucket: 'rentailappfl.firebasestorage.app',
    measurementId: 'G-Y3CNFFJ8ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFQSURwKhdzUI28XsCFJPZiQlunEaOSc',
    appId: '1:858390713760:android:79a2401568be675c7b40c5',
    messagingSenderId: '858390713760',
    projectId: 'rentailappfl',
    storageBucket: 'rentailappfl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYTnp76MV6NdUF-cyJqGjO73hlrEz-J4',
    appId: '1:858390713760:ios:089e7c4d23b62f3b7b40c5',
    messagingSenderId: '858390713760',
    projectId: 'rentailappfl',
    storageBucket: 'rentailappfl.firebasestorage.app',
    iosBundleId: 'com.marlon.rentailapp.rentail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWYTnp76MV6NdUF-cyJqGjO73hlrEz-J4',
    appId: '1:858390713760:ios:089e7c4d23b62f3b7b40c5',
    messagingSenderId: '858390713760',
    projectId: 'rentailappfl',
    storageBucket: 'rentailappfl.firebasestorage.app',
    iosBundleId: 'com.marlon.rentailapp.rentail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC2dJCDVZVMRYjHQHRKE-FyTPipZXPSL4',
    appId: '1:858390713760:web:4d287d394b12298e7b40c5',
    messagingSenderId: '858390713760',
    projectId: 'rentailappfl',
    authDomain: 'rentailappfl.firebaseapp.com',
    storageBucket: 'rentailappfl.firebasestorage.app',
    measurementId: 'G-H2JYB3RVD9',
  );
}
